export const newsCategories = [
  'business',
  'entertainment',
  'environment',
  'food',
  'health',
  'politics',
  'science',
  'sports',
  'technology',
  'top',
  'tourism',
  'world',
];
export const newsCountry = [
  { label: 'Afghanistan', value: 'af' },
  { label: 'Albania', value: 'al' },
  { label: 'Algeria', value: 'dz' },
  { label: 'Angola', value: 'ao' },
  { label: 'Argentina', value: 'ar' },
  { label: 'Australia', value: 'au' },
  { label: 'Austria', value: 'at' },
  { label: 'Azerbaijan', value: 'az' },
  { label: 'Bahrain', value: 'bh' },
  { label: 'Bangladesh', value: 'bd' },
  { label: 'Barbados', value: 'bb' },
  { label: 'Belarus', value: 'by' },
  { label: 'Belgium', value: 'be' },
  { label: 'Bermuda', value: 'bm' },
  { label: 'Bhutan', value: 'bt' },
  { label: 'Bolivia', value: 'bo' },
  { label: 'Brazil', value: 'br' },
  { label: 'Brunei', value: 'bn' },
  { label: 'Bulgaria', value: 'bg' },
  { label: 'Cambodia', value: 'kh' },
  { label: 'Cameroon', value: 'cm' },
  { label: 'Canada', value: 'ca' },
  { label: 'Chile', value: 'cl' },
  { label: 'China', value: 'cn' },
  { label: 'Colombia', value: 'co' },
  { label: 'Comoros', value: 'km' },
  { label: 'Croatia', value: 'hr' },
  { label: 'Cuba', value: 'cu' },
  { label: 'Cyprus', value: 'cy' },
  { label: 'Czech republic', value: 'cz' },
  { label: 'Denmark', value: 'dk' },
  { label: 'Djibouti', value: 'dj' },
  { label: 'Dominica', value: 'dm' },
  { label: 'Dominican republic', value: 'do' },
  { label: 'DR Congo', value: 'cd' },
  { label: 'Ecuador', value: 'ec' },
  { label: 'Egypt', value: 'eg' },
  { label: 'El Salvador', value: 'sv' },
  { label: 'Estonia', value: 'ee' },
  { label: 'Ethiopia', value: 'et' },
  { label: 'Fiji', value: 'fj' },
  { label: 'Finland', value: 'fi' },
  { label: 'France', value: 'fr' },
  { label: 'French polynesia', value: 'pf' },
  { label: 'Gabon', value: 'ga' },
  { label: 'Georgia', value: 'ge' },
  { label: 'Germany', value: 'de' },
  { label: 'Ghana', value: 'gh' },
  { label: 'Greece', value: 'gr' },
  { label: 'Guatemala', value: 'gt' },
  { label: 'Guinea', value: 'gn' },
  { label: 'Haiti', value: 'ht' },
  { label: 'Honduras', value: 'hn' },
  { label: 'Hong Kong', value: 'hk' },
  { label: 'Hungary', value: 'hu' },
  { label: 'Iceland', value: 'is' },
  { label: 'India', value: 'in' },
  { label: 'Indonesia', value: 'id' },
  { label: 'Iraq', value: 'iq' },
  { label: 'Ireland', value: 'ie' },
  { label: 'Israel', value: 'il' },
  { label: 'Italy', value: 'it' },
  { label: 'Jamaica', value: 'jm' },
  { label: 'Japan', value: 'jp' },
  { label: 'Jordan', value: 'jo' },
  { label: 'Kazakhstan', value: 'kz' },
  { label: 'Kenya', value: 'ke' },
  { label: 'Kuwait', value: 'kw' },
  { label: 'Kyrgyzstan', value: 'kg' },
  { label: 'Latvia', value: 'lv' },
  { label: 'Lebanon', value: 'lb' },
  { label: 'Libya', value: 'ly' },
  { label: 'Lithuania', value: 'lt' },
  { label: 'Luxembourg', value: 'lu' },
  { label: 'Macau', value: 'mo' },
  { label: 'Macedonia', value: 'mk' },
  { label: 'Madagascar', value: 'mg' },
  { label: 'Malawi', value: 'mw' },
  { label: 'Maldives', value: 'mv' },
  { label: 'Mali', value: 'ml' },
  { label: 'Malta', value: 'mt' },
  { label: 'Mauritania', value: 'mr' },
  { label: 'Mexico', value: 'mx' },
  { label: 'Moldova', value: 'md' },
  { label: 'Mongolia', value: 'mn' },
  { label: 'Montenegro', value: 'me' },
  { label: 'Morocco', value: 'ma' },
  { label: 'Mozambique', value: 'mz' },
  { label: 'Myanmar', value: 'mm' },
  { label: 'Namibia', value: 'na' },
  { label: 'Nepal', value: 'np' },
  { label: 'Netherlands', value: 'nl' },
  { label: 'New Zealand', value: 'nz' },
  { label: 'Niger', value: 'ne' },
  { label: 'Nigeria', value: 'ng' },
  { label: 'North Korea', value: 'kp' },
  { label: 'Norway', value: 'no' },
  { label: 'Oman', value: 'om' },
  { label: 'Pakistan', value: 'pk' },
  { label: 'Panama', value: 'pa' },
  { label: 'Paraguay', value: 'py' },
  { label: 'Peru', value: 'pe' },
  { label: 'Philippines', value: 'ph' },
  { label: 'Poland', value: 'pl' },
  { label: 'Portugal', value: 'pt' },
  { label: 'Puerto Rico', value: 'pr' },
  { label: 'Romania', value: 'ro' },
  { label: 'Russia', value: 'ru' },
  { label: 'Rwanda', value: 'rw' },
  { label: 'Samoa', value: 'ws' },
  { label: 'San Marino', value: 'sm' },
  { label: 'Saudi Arabia', value: 'sa' },
  { label: 'Senegal', value: 'sn' },
  { label: 'Serbia', value: 'rs' },
  { label: 'Singapore', value: 'sg' },
  { label: 'Slovakia', value: 'sk' },
  { label: 'Slovenia', value: 'si' },
  { label: 'Solomon Islands', value: 'sb' },
  { label: 'Somalia', value: 'so' },
  { label: 'South Africa', value: 'za' },
  { label: 'South Korea', value: 'kr' },
  { label: 'Spain', value: 'es' },
  { label: 'Sri Lanka', value: 'lk' },
  { label: 'Sudan', value: 'sd' },
  { label: 'Sweden', value: 'se' },
  { label: 'Switzerland', value: 'ch' },
  { label: 'Syria', value: 'sy' },
  { label: 'Taiwan', value: 'tw' },
  { label: 'Tajikistan', value: 'tj' },
  { label: 'Tanzania', value: 'tz' },
  { label: 'Thailand', value: 'th' },
  { label: 'Tonga', value: 'to' },
  { label: 'Tunisia', value: 'tn' },
  { label: 'Turkey', value: 'tr' },
  { label: 'Turkmenistan', value: 'tm' },
  { label: 'Uganda', value: 'ug' },
  { label: 'Ukraine', value: 'ua' },
  { label: 'United Arab Emirates', value: 'ae' },
  { label: 'United Kingdom', value: 'gb' },
  { label: 'United States of America', value: 'us' },
  { label: 'Uruguay', value: 'uy' },
  { label: 'Uzbekistan', value: 'uz' },
  { label: 'Venezuela', value: 've' },
  { label: 'Vietnam', value: 'vi' },
  { label: 'Yemen', value: 'ye' },
  { label: 'Zambia', value: 'zm' },
  { label: 'Zimbabwe', value: 'zw' },
];

export const newsLanguages = [
  { label: 'Afrikaans', value: 'af' },
  { label: 'Albanian', value: 'sq' },
  { label: 'Amharic', value: 'am' },
  { label: 'Arabic', value: 'ar' },
  { label: 'Armenian', value: 'hy' },
  { label: 'Assamese', value: 'as' },
  { label: 'Azerbaijani', value: 'az' },
  { label: 'Basque', value: 'eu' },
  { label: 'Belarusian', value: 'be' },
  { label: 'Bengali', value: 'bn' },
  { label: 'Bosnian', value: 'bs' },
  { label: 'Bulgarian', value: 'bg' },
  { label: 'Burmese', value: 'my' },
  { label: 'Catalan', value: 'ca' },
  { label: 'Central Kurdish', value: 'ckb' },
  { label: 'Chinese', value: 'zh' },
  { label: 'Croatian', value: 'hr' },
  { label: 'Czech', value: 'cs' },
  { label: 'Danish', value: 'da' },
  { label: 'Dutch', value: 'nl' },
  { label: 'English', value: 'en' },
  { label: 'Estonian', value: 'et' },
  { label: 'Filipino', value: 'pi' },
  { label: 'Finnish', value: 'fi' },
  { label: 'French', value: 'fr' },
  { label: 'Georgian', value: 'ka' },
  { label: 'German', value: 'de' },
  { label: 'Greek', value: 'el' },
  { label: 'Gujarati', value: 'gu' },
  { label: 'Hebrew', value: 'he' },
  { label: 'Hindi', value: 'hi' },
  { label: 'Hungarian', value: 'hu' },
  { label: 'Icelandic', value: 'is' },
  { label: 'Indonesian', value: 'id' },
  { label: 'Italian', value: 'it' },
  { label: 'Japanese', value: 'jp' },
  { label: 'Kannada', value: 'kn' },
  { label: 'Khmer', value: 'kh' },
  { label: 'Kinyarwanda', value: 'rw' },
  { label: 'Korean', value: 'ko' },
  { label: 'Latvian', value: 'lv' },
  { label: 'Lithuanian', value: 'lt' },
  { label: 'Luxembourgish', value: 'lb' },
  { label: 'Macedonian', value: 'mk' },
  { label: 'Malay', value: 'ms' },
  { label: 'Malayalam', value: 'ml' },
  { label: 'Maltese', value: 'mt' },
  { label: 'Maori', value: 'mi' },
  { label: 'Marathi', value: 'mr' },
  { label: 'Mongolian', value: 'mn' },
  { label: 'Nepali', value: 'ne' },
  { label: 'Norwegian', value: 'no' },
  { label: 'Oriya', value: 'or' },
  { label: 'Pashto', value: 'ps' },
  { label: 'Persian', value: 'fa' },
  { label: 'Polish', value: 'pl' },
  { label: 'Portuguese', value: 'pt' },
  { label: 'Punjabi', value: 'pa' },
  { label: 'Romanian', value: 'ro' },
  { label: 'Russian', value: 'ru' },
  { label: 'Samoan', value: 'sm' },
  { label: 'Serbian', value: 'sr' },
  { label: 'Shona', value: 'sn' },
  { label: 'Sinhala', value: 'si' },
  { label: 'Slovak', value: 'sk' },
  { label: 'Slovenian', value: 'sl' },
  { label: 'Somali', value: 'so' },
  { label: 'Spanish', value: 'es' },
  { label: 'Swahili', value: 'sw' },
  { label: 'Swedish', value: 'sv' },
  { label: 'Tajik', value: 'tg' },
  { label: 'Tamil', value: 'ta' },
  { label: 'Telugu', value: 'te' },
  { label: 'Thai', value: 'th' },
  { label: 'Turkish', value: 'tr' },
  { label: 'Turkmen', value: 'tk' },
  { label: 'Ukrainian', value: 'uk' },
  { label: 'Urdu', value: 'ur' },
  { label: 'Uzbek', value: 'uz' },
  { label: 'Vietnamese', value: 'vi' },
  { label: 'Welsh', value: 'cy' },
];
